import { resolve, relative } from 'path';
import {
  mkdirSync,
  existsSync,
  writeFileSync,
  readFileSync,
  readdirSync,
  rmdirSync,
  unlinkSync,
} from 'fs';
import { join } from 'path';

import type { ApigConfig, ApigPlugin, GenerationStats } from '@models';
import { logger } from '@libs/logger';

import { typescript, sdk, faker, zod, tanstackQuery, msw } from '@plugins';

export type WriteFn = (
  filename: string,
  content: string,
  outputDir: string,
) => void;

const DEFAULT_PLUGINS: ApigPlugin[] = [
  typescript(),
  sdk(),
  faker(),
  zod(),
  tanstackQuery(),
  msw(),
];

export const resolvePlugins = (config: ApigConfig): ApigPlugin[] =>
  config.plugins ?? DEFAULT_PLUGINS;

const DEFAULT_OUTPUT = '.apig/generated';

export const resolveOutputPath = (config: ApigConfig): string => {
  if (!config.output) return resolve(DEFAULT_OUTPUT);
  return typeof config.output === 'string'
    ? resolve(config.output)
    : resolve(config.output.path);
};

/** Present in the banner of every file this generator writes. */
const GENERATED_MARKER = 'auto-generated by @travjek/apig';

const isGenerated = (path: string): boolean => {
  try {
    return readFileSync(path, 'utf-8').slice(0, 200).includes(GENERATED_MARKER);
  } catch {
    return false;
  }
};

/**
 * Deletes previously generated files under `dir`, leaving anything else alone,
 * and reports what was left behind. Returns true when the directory ended up
 * empty and can be removed.
 */
const removeGenerated = (
  dir: string,
  stats: GenerationStats,
  foreign: string[],
): boolean => {
  let empty = true;

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);

    if (entry.isDirectory()) {
      if (removeGenerated(path, stats, foreign)) rmdirSync(path);
      else empty = false;
      continue;
    }

    if (isGenerated(path)) {
      unlinkSync(path);
      stats.deletedFiles++;
    } else {
      foreign.push(path);
      empty = false;
    }
  }

  return empty;
};

/**
 * Clears the output directory before a run.
 *
 * Only files carrying the generator's banner are removed — an output folder
 * frequently sits next to hand-written code, and `clean` being on by default
 * must not take that with it.
 */
export const cleanOutput = (
  outputPath: string,
  config: ApigConfig,
  stats: GenerationStats,
): void => {
  const shouldClean =
    !config.output || typeof config.output === 'string'
      ? true
      : (config.output.clean ?? true);

  if (shouldClean && existsSync(outputPath)) {
    const foreign: string[] = [];
    removeGenerated(outputPath, stats, foreign);

    if (foreign.length > 0) {
      const shown = foreign
        .slice(0, 5)
        .map((p) => relative(outputPath, p))
        .join(', ');
      const rest = foreign.length > 5 ? `, +${foreign.length - 5} more` : '';
      logger.warn(
        `kept ${foreign.length} file(s) in the output directory not written by apig: ${shown}${rest}`,
      );
    }
  }

  mkdirSync(outputPath, { recursive: true });
};

export const makeWriteFn = (
  stats: GenerationStats,
  dryRun: boolean,
): WriteFn => {
  return (filename: string, content: string, outputDir: string): void => {
    if (dryRun) {
      logger.detail(
        `Would write: ${join(outputDir, filename).replace(process.cwd() + '/', '')}`,
      );
      stats.createdFiles++;
      return;
    }
    const fullPath = join(outputDir, filename);
    const isUpdate = existsSync(fullPath);
    writeFileSync(fullPath, content, 'utf-8');
    if (isUpdate) {
      stats.updatedFiles++;
    } else {
      stats.createdFiles++;
    }
    logger.detail(`  ${isUpdate ? 'Updated' : 'Created'}: ${filename}`);
  };
};
